import type { InfluencerSuggestion } from '@/components/campaign-flow/CampaignContext';

export const DUMMY_INFLUENCER: InfluencerSuggestion = {
    id: 'dummy_aditya_001',
    name: 'Aditya',
    handle: '@instagram',
    platform: 'Instagram',
    followers: '52K',
    niche: 'Tech & Lifestyle',
    pricePerPost: '₹8,000–₹15,000',
    location: 'Mumbai',
    matchScore: 91,
    engagementRate: '6.2%',
    avatar: '',
    tier: 'A',
    email: 'iamarnav3101@gmail.com',
    phone: null,
    instagramUrl: 'https://www.instagram.com/aditya',
    whySuggested: 'Aditya blends tech reviews with relatable lifestyle content, making him a perfect fit for brands targeting digitally-savvy urban audiences. His authentic voice drives above-average engagement.',
    expectedROI: 'Expected 4–6x ROI based on engagement rate (6.2%) and audience match score of 91%. Strong conversion potential in the 18–28 age bracket.',
    performanceBenefits: 'High audience trust, niche authority in tech, strong India-first audience (82%), and consistent posting history with brand collaborations.',
    vibe: 'Authentic, Aspirational, Tech-forward',
    brandFit: 'D2C, Tech, Lifestyle, Mobile, E-commerce',
    mfSplit: '62% Male / 38% Female',
    indiaSplit: '82% India / 18% Global',
    ageGroup: '18–28 years',
    avgViews: '28K',
    scoreBreakdown: {
        relevance: { score: 92 },
        engagement: { score: 88 },
        reach: { score: 85 },
        authenticity: { score: 95 },
    },
    executionSteps: [
        'Initial outreach via email or DM',
        'Share campaign brief & mood board',
        'Content creation & 1 review round',
        'Publish and track performance metrics',
    ],
};
